name: aqua-marina
channels:
  - conda-forge
dependencies:
  - black
  - imageio
  - ipykernel # required for jupyter notebook in VS Code
  - ipympl
  - matplotlib
  - pillow
  - pip
  - pytest
  - python=3.11
  - ruff
  - scikit-image
